bind-address = "localhost"
bind-port = 3000
master-secret = "1kY4Zcx/Np74XZnI/G8h1vq74NwrtpLF3PW96g9RWo0"
id-encoder-secret = "VGhpcyBpcyBhIFQzc3QhCg"

[database]
db-url = "postgres://lzdadmin:lzadmin1@localhost/postgres"
max-open = 20
max-idle = 4
max-lifetime = "4 hours"
max-idle-lifetime = "15 minutes"
timeout-for-get = "30 seconds"

[jobs.email-verification]
run = true
sleep = "15 seconds"
error-sleep = "180 seconds"
smtp-connect-timeout = "5 seconds"
smtp-implicit-tls = false
smtp-user-name = ""
smtp-password = ""

[tracing]
console = false
