[package]
name = "gen-master-key"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
aes-gcm-siv.workspace = true
anyhow.workspace = true
base64.workspace = true
crypto-common.workspace = true

[lints]
workspace = true
